version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: weather_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  etl_app:
    build:
      context: ./app
    container_name: weather_etl_app
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    command: [ "bash", "entrypoint.sh" ]

volumes:
  postgres_data:
